---
title: "Untitled"
author: "Matthew Hofkes"
date: "2023-07-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
x <- 1:10.  # 1 to number of obsevations
y <- 4 + .5*x + .1*x^2 + rnorm(10)
plot(x,y)
```


```{r}
model <- lm(y ~ x +I(x^2))
summary(model)
plot(x,y)
points(x,model$fitted.values,type="l",col="red")
points(x,model$fitted.values,col="red")
X <- cbind(1,x) # data frame with a leading column of ones
B <- solve(t(X)%*%X) %*% t(X)%*%y
y.pred <- X%*% solve(t(X)%*%X) %*% t(X)%*%y
plot(x,y.pred)
H <- X%*% solve(t(X)%*%X) %*% t(X) # diagonal of H is the variance of each pred value
variances <- diag(H)
CI <- sqrt(variances)*1.96
```

```{r}
plot(x,y)
points(x,model$fitted.values,type="l",col="red")
points(x,model$fitted.values,col="red")
points(x,model$fitted.values+CI,type="l",col="red")
points(x,model$fitted.values-CI,type="l",col="red")

upper <- model$fitted.values+CI
lower <- model$fitted.values-CI
n <- 10
plot(x,y,ylim=c(4,22))
points(x,y.pred,col="red")
for (i in 1:n){
  segments(x[i],lower[i],x[i],upper[i],col="red")
}
```

