---
title: "EPS and SRT Wrangling"
author: "Kate Pogue"
date: "2023-06-16"
output: html_document
---


Loading Packages
```{r}
library(tidyverse)
library(Metrics)
library(tidyr)
library(dplyr)
library(olsrr)
library(openxlsx)
library(readxl)
library(lubridate)
```

Loading Data
```{r}
NAB2 <- read_csv("data/NAB2_VER3.csv")
EPS <- read_excel("data/all_EPS.xlsx")
ASRT_main <- read_excel("data/ASRT_main.xlsx")
ASRT_other <- read_excel("data/ASRT_other.xlsx")
```





make e. coli reduction variable and wrangle ASRT
```{r}
# Convert "timestamp" column to a date vector
ASRT_main$timestamp <- as.Date(ASRT_main$timestamp, format = "%Y/%m/%d")
ASRT_other$timestamp <- as.Date(ASRT_other$timestamp, format = "%Y/%m/%d")


#select relevant variables
ecoli <- NAB2 %>% select(timestamp,
                         "NAB2 Clarifier Effluent E. coli (LAB) (EC/100mL)", 
                         "NAB4 Clarifier Effluent E. coli (LAB) (EC/100mL)", 
                         "NSI E. coli (LAB) (EC/100mL)", 
                         "NAB9 Clarifier Effluent E. coli (LAB) (EC/100mL)")

#merge the basin 4 and 9 data
ecoli$`NAB4 Clarifier Effluent E. coli (LAB) (EC/100mL)`[is.na(ecoli$`NAB4 Clarifier Effluent E. coli (LAB) (EC/100mL)`)] <- 0
ecoli$`NAB9 Clarifier Effluent E. coli (LAB) (EC/100mL)`[is.na(ecoli$`NAB9 Clarifier Effluent E. coli (LAB) (EC/100mL)`)] <- 0

ecoli <- mutate(ecoli, "NAB4 and 9 Clarifier Effluent E. coli (LAB) (EC/100mL)" = 
              (ecoli$`NAB4 Clarifier Effluent E. coli (LAB) (EC/100mL)` + ecoli$'NAB9 Clarifier Effluent E. coli (LAB) (EC/100mL)'))

ecoli$'NAB4 and 9 Clarifier Effluent E. coli (LAB) (EC/100mL)'[ecoli$'NAB4 and 9 Clarifier Effluent E. coli (LAB) (EC/100mL)' == 0] <- NA
ecoli <- ecoli %>% select(-'NAB4 Clarifier Effluent E. coli (LAB) (EC/100mL)', -'NAB9 Clarifier Effluent E. coli (LAB) (EC/100mL)')

## make LOG reduction variable
ecoli$log_pilot_reduction <- log(ecoli$`NSI E. coli (LAB) (EC/100mL)`, base = 10)- log(ecoli$`NAB2 Clarifier Effluent E. coli (LAB) (EC/100mL)`, base = 10)

ecoli$log_control_reduction <- log(ecoli$`NSI E. coli (LAB) (EC/100mL)`, base = 10)-log(ecoli$`NAB4 and 9 Clarifier Effluent E. coli (LAB) (EC/100mL)`, base = 10)


## normal effluent variables just need to be log transformed
ecoli$log_pilot_ecoli <- log(ecoli$`NAB2 Clarifier Effluent E. coli (LAB) (EC/100mL)`, base = 10)
ecoli$log_control_ecoli <- log(ecoli$`NAB4 and 9 Clarifier Effluent E. coli (LAB) (EC/100mL)`, base = 10)


#only select useful variables
ecoli <- ecoli %>% select(timestamp, 
                          log_pilot_reduction, 
                          log_control_reduction, 
                          log_pilot_ecoli, 
                          log_control_ecoli)

ecoli<- na.omit(ecoli)


#look at distributions
ggplot() +
  geom_density(data = ecoli, aes(x = log_pilot_ecoli), color = "red", fill = "red", alpha = 0.3) +
  geom_density(data = ecoli, aes(x = log_control_ecoli), color = "blue", fill = "blue", alpha = 0.3) +
  geom_density(data = ecoli, aes(x = log_pilot_reduction), color = "green", fill = "green", alpha = 0.3) +
  geom_density(data = ecoli, aes(x = log_control_reduction), color = "orange", fill = "orange", alpha = 0.3) +
  xlab("Value") +
  ylab("Density") +
  ggtitle("Densities of Ecoli Variables") +
  theme_minimal()


# Plot Reductions as line graphs
ggplot(ecoli, aes(x = timestamp)) +
  geom_line(aes(y = log_pilot_reduction, color = "Pilot")) +
  geom_line(aes(y = log_control_reduction, color = "Control")) +
  labs(x = "Timestamp", y = "E. coli reduction (EC/100mL)",
       title = "E. coli Reduction Timeseries") +
  scale_color_manual(values = c("blue", "red")) +
  theme_minimal()
```



PILOT: Wrangle EPS 
```{r}
#rename timestamp
EPS <- EPS %>% rename(timestamp = 1)

#select pilot variables
pilot_eps <- EPS %>% select(timestamp, starts_with("Pilot"))

#get NAB2 factors
others <- NAB2 %>% select(timestamp,
                          "Clarifier 2 SLR (ppd/sf)",                          
                          "Clarifier 2 SOR (gpd/sf)",                              
                          "NAB2 C-Pass Total COD (LAB) (mg/L)",
                          "NAB2 C-Pass TKNH (LAB) (mg/L)",
                          "NAB2 C-Pass TSS (LAB) (mg/L)",
                          "NAB2 C-Pass VSS (LAB) (mg/L)", 
                          "AB2A DO (mg/L)", 
                          "AB2B DO (mg/L)",
                          "AB2C DO (mg/L)",
                          "AB2A NO5 (mgN/L)", 
                          "AB2A NH3 (mg N/L)", 
                          "AB2C NH3 (mg N/L)" , 
                          "AB2C MLSS (mg/L)", 
                          "AB2 INF FLOW (MGD)", 
                          "AB2 MLR FLOW (MGD)", 
                          "AB2A AIRFLOW (SCFM)", 
                          "AB2B AIRFLOW (SCFM)", 
                          "AB2C AIRFLOW (SCFM)", 
                          "SC2 BLANKET (ft)", 
                          "NAB2 C-Pass dSVI 30 (mL/g)", 
                          "NAB2 C-Pass dSVI 5 (mL/g)"  
                          ,"NAB2 Clarifier Effluent Total COD (Low Level) (LAB) (mg/L)"  
,"NAB2 Clarifier Effluent NH3 (LAB) (mg/L)"                  
,"NAB2 Clarifier Effluent NO2 (LAB) (mg/L)"                  
,"NAB2 Clarifier Effluent NO5 (LAB) (mg/L)"                  
,"NAB2 Clarifier Effluent OP (LAB) (mg/L)"                             
,"NAB2 Clarifier Effluent PWS (LAB) (mg/L)"                  
,"NAB2 Clarifier Effluent PW (LAB) (mg/L)"                   
,"NAB2 Clarifier Effluent TKNH (LAB) (mg/L)"                 
,"NAB2 Clarifier Effluent TSS (LAB) (mg/L)"                  
,"NAB2 Clarifier Effluent VSS (LAB) (mg/L)"
                          )

colnames(others) <- c(
  "timestamp",
  "CLARIFIER_2_SLR",
  "CLARIFIER_2_SOR",
  "NAB2_CPASS_TOTAL_COD",
  "NAB2_CPASS_TKNH",
  "NAB2_CPASS_TSS",
  "NAB2_CPASS_VSS",
  "AB2A_DO",
  "AB2B_DO",
  "AB2C_DO",
  "AB2A_NO5",
  "AB2A_NH3",
  "AB2C_NH3",
  "AB2C_MLSS",
  "AB2_INF_FLOW",
  "AB2_MLR_FLOW",
  "AB2A_AIRFLOW",
  "AB2B_AIRFLOW",
  "AB2C_AIRFLOW",
  "SC2_BLANKET",
  "NAB2_CPASS_dSVI30",
  "NAB2_CPASS_dSVI5",
  "NAB2_CLARIFIER_EFFLUENT_TOTAL_COD",
  "NAB2_CLARIFIER_EFFLUENT_NH3",
  "NAB2_CLARIFIER_EFFLUENT_NO2",
  "NAB2_CLARIFIER_EFFLUENT_NO5",
  "NAB2_CLARIFIER_EFFLUENT_OP",
  "NAB2_CLARIFIER_EFFLUENT_PWS",
  "NAB2_CLARIFIER_EFFLUENT_PW",
  "NAB2_CLARIFIER_EFFLUENT_TKNH",
  "NAB2_CLARIFIER_EFFLUENT_TSS",
  "NAB2_CLARIFIER_EFFLUENT_VSS"
)

others$"AB2_INF_FLOW"[others$"AB2_INF_FLOW" == 0] <- NA

others <- others %>%
  mutate(across(-1, ~ ifelse(row_number() >= 1, na.locf(.), .)))

#get general NAB2 variables
general <- NAB2 %>% select ( timestamp,
                             "NSEC ACTUAL ASRT (days)",
                             "Solids Wasted via Effluent (tpd)",
                             "Solids Wasted via SWAS (tpd)",
                             "Solids Wasted via WAS (tpd)",
                             "NSEC MIN ASRT (days)",
                             "Total Solids Wasted (tpd)",
                             "NSI Soluble COD (LAB) (mg/L)",
                             "NSI Total COD (LAB) (mg/L)",
                             "NSI E. coli (LAB) (EC/100mL)",
                             "NSI NH3A (LAB) (mg/L)",
                             "NSI NO2 (LAB) (mg/L)",
                             "NSI NO5 (LAB) (mg/L)",
                             "NSI OP (LAB) (mg/L)",
                             "NSI PWS (LAB) (mg/L)",
                             "NSI PW (LAB) (mg/L)",
                             "NSI TKNH (LAB) (mg/L)",
                             "NSI TSS (LAB) (mg/L)",
                             "NSI TVAH (LAB) (mg/L)",
                             "NSI VSS (LAB) (mg/L)",
                             "NSEC EFF TSS (mg/L)",
                             "NSI NH3 (mg N/L)",
                             "NSI TSS (mg/L)",
                             "NSI COD (mg/L)",
                             "NSI sCOD (mg/L)",
                             "NSI FLOW (MGD)",
                             "NSI TEMP (C)"
)

general <- general %>%
  mutate(across(-1, ~ ifelse(row_number() >= 1, na.locf(.), .)))

#get ASRT-other variables for pilot
ASRT_other_pilot <- ASRT_other %>% select(timestamp, starts_with("Pilot"))
colnames(ASRT_other_pilot) <- c("timestamp",
                                "Pilot_ASRT_d",
                                "Pilot_Floc_SRT_d",
                                "Pilot_Granule_SRT_d",
                                "Pilot_AGS_Weighted_SRT_d",
                                "Pilot_Floc_percent",
                                "Pilot_Granule_percent")

ASRT_other_pilot <- ASRT_other_pilot %>%
  fill(everything())

#select pilot ecoli
pilot_ecoli <- ecoli %>% select(timestamp, "log_pilot_reduction", "log_pilot_ecoli")
pilot_factors <- left_join(pilot_ecoli, pilot_eps, by = "timestamp")
colnames(pilot_factors) <- c("timestamp", "log_pilot_reduction", "log_pilot_ecoli", "pilot_total_cod_mgcod_per_gvss",
                  "pilot_total_pn_to_ps", "pilot_lb_cod_mgcod_per_gvss",
                  "pilot_lb_proteins_mg_per_gvss", "pilot_lb_carbs_mg_per_gvss",
                  "pilot_tb_cod_mgcod_per_gvss", "pilot_tb_proteins_mg_per_gvss",
                  "pilot_tb_carbs_mgcarb_per_gvss", "pilot_tb_pn_to_ps")


#FILL method to fill in missing EPS and ASRT values
pilot_eps_filled <- left_join(pilot_factors, others, by = "timestamp")
pilot_eps_filled <- left_join(pilot_eps_filled, general, by = "timestamp")
pilot_eps_filled <- left_join(pilot_eps_filled, ASRT_main[,-3], by = "timestamp")
pilot_eps_filled <- left_join(pilot_eps_filled, ASRT_other_pilot, by = "timestamp")
pilot_eps_filled <- pilot_eps_filled %>% fill(-c("Pilot_NAB2_ASRT", "pilot_total_cod_mgcod_per_gvss",
                  "pilot_total_pn_to_ps", "pilot_lb_cod_mgcod_per_gvss",
                  "pilot_lb_proteins_mg_per_gvss", "pilot_lb_carbs_mg_per_gvss",
                  "pilot_tb_cod_mgcod_per_gvss", "pilot_tb_proteins_mg_per_gvss",
                  "pilot_tb_carbs_mgcarb_per_gvss", "pilot_tb_pn_to_ps")
                                              , .direction = "down")
pilot_eps_filled <- pilot_eps_filled[-c(1:7),]
pilot_eps_filled <- pilot_eps_filled %>% fill(everything(), .direction = "down")


#REMOVE method
pilot_eps_removed <- left_join(pilot_factors, others, by = "timestamp")
pilot_eps_removed <- left_join(pilot_eps_removed, general, by = "timestamp")
pilot_eps_removed <- left_join(pilot_eps_removed, ASRT_main[,-3], by = "timestamp")
pilot_eps_removed <- left_join(pilot_eps_removed, ASRT_other_pilot, by = "timestamp")
pilot_eps_removed <- na.omit(pilot_eps_removed)

```


Control: Wrangle EPS 
```{r}
#rename timestamp
EPS <- EPS %>% rename(timestamp = 1)

#select control variables
control_eps <- EPS %>% select(timestamp, starts_with("Control"))


#get NAB2 factors
others <- NAB2 %>% select(timestamp,
"Clarifier 9 SLR (ppd/sf)"                                  
,"Clarifier 9 SOR (gpd/sf)"    
,"NAB9 C-Pass Total COD (LAB) (mg/L)"       
,"NAB4 C-Pass TKNH (LAB) (mg/L)"
,"NAB9 C-Pass TKNH (LAB) (mg/L)"             
,"NAB9 C-Pass TSS (LAB) (mg/L)"      
,"NAB9 C-Pass VSS (LAB) (mg/L)"   
,"AB9A DO (mg/L)"      
,"AB9B DO (mg/L)"                                            
,"AB9C DO (mg/L)" 
,"AB9A NO5 (mg N/L)"   
,"AB9A NH3 (mg N/L)"   
,"AB9C NH3 (mg N/L)"  
,"AB9C MLSS (mg/L)" 
,"AB9 INF FLOW (MGD)"   
,"AB9 MLR FLOW (MGD)"   
,"AB9A AIRFLOW (SCFM)"   
,"AB9B AIRFLOW (SCFM)"                                       
,"AB9C AIRFLOW (SCFM)"   
,"SC9 BLANKET (ft)"      
,"NAB4 C-Pass dSVI 30 (mL/g)"    
,"NAB9 C-Pass dSVI 30 (mL/g)"                                
,"NAB4 C-Pass dSVI 5 (mL/g)"
,"NAB9 C-Pass dSVI 5 (mL/g)"
,"NAB4 C-Pass TSS (LAB) (mg/L)"
,"NAB4 C-Pass VSS (LAB) (mg/L)"
,"NAB4 C-Pass Total COD (LAB) (mg/L)"
,"AB4A NO5 (mg N/L)"
,"AB4A NH3 (mg N/L)" 
,"AB4C NH3 (mg N/L)" 
,"AB4C MLSS (mg N/L)" 
,"AB4 INF FLOW (MGD)"  
,"AB4 MLR FLOW (MGD)"
,"NNE Total COD (Low Level) (LAB) (mg/L)"                     
,"NNE NH3A (LAB) (mg/L)"                                     
,"NNE NO2 (LAB) (mg/L)"                                       
,"NNE NO5 (LAB) (mg/L)"                                      
,"NNE OP (LAB) (mg/L)"                                        
,"NNE PWS (LAB) (mg/L)"                                      
,"NNE PW (LAB) (mg/L)"                                       
,"NNE TKNH (LAB) (mg/L)"                                     
,"NNE TSS (LAB) (mg/L)"                                       
,"NNE VSS (LAB) (mg/L)"
                          )


#combine variables from 4 and 9


others$`NAB4 C-Pass TKNH (LAB) (mg/L)`[is.na(others$`NAB4 C-Pass TKNH (LAB) (mg/L)`)] <- 0
others$`NAB9 C-Pass TKNH (LAB) (mg/L)`[is.na(others$`NAB9 C-Pass TKNH (LAB) (mg/L)`)] <- 0

others <- mutate(others, "NAB4 and 9 C-Pass TKNH (LAB) (mg/L)" = 
              (others$`NAB4 C-Pass TKNH (LAB) (mg/L)` + others$`NAB9 C-Pass TKNH (LAB) (mg/L)`))

others$'NAB4 and 9 C-Pass TKNH (LAB) (mg/L)'[others$'NAB4 and 9 C-Pass TKNH (LAB) (mg/L)' == 0] <- NA
others <- others %>% select(-'NAB4 C-Pass TKNH (LAB) (mg/L)', -'NAB9 C-Pass TKNH (LAB) (mg/L)')

# c-pass dsvi 30

others$`NAB4 C-Pass dSVI 30 (mL/g)`[is.na(others$`NAB4 C-Pass dSVI 30 (mL/g)`)] <- 0
others$`NAB9 C-Pass dSVI 30 (mL/g)`[is.na(others$`NAB9 C-Pass dSVI 30 (mL/g)`)] <- 0

others <- mutate(others, "NAB4 and 9 C-Pass dSVI 30 (mL/g)" = 
              (others$`NAB4 C-Pass dSVI 30 (mL/g)` + others$`NAB9 C-Pass dSVI 30 (mL/g)`))

others$'NAB4 and 9 C-Pass dSVI 30 (mL/g)'[others$'NAB4 and 9 C-Pass dSVI 30 (mL/g)' == 0] <- NA
others <- others %>% select(-'NAB4 C-Pass dSVI 30 (mL/g)', -'NAB9 C-Pass dSVI 30 (mL/g)')

#c-pass dsvi 5

others$`NAB4 C-Pass dSVI 5 (mL/g)`[is.na(others$`NAB4 C-Pass dSVI 5 (mL/g)`)] <- 0
others$`NAB9 C-Pass dSVI 5 (mL/g)`[is.na(others$`NAB9 C-Pass dSVI 5 (mL/g)`)] <- 0

others <- mutate(others, "NAB4 and 9 C-Pass dSVI 5 (mL/g)" = 
              (others$`NAB4 C-Pass dSVI 5 (mL/g)` + others$`NAB9 C-Pass dSVI 5 (mL/g)`))

others$'NAB4 and 9 C-Pass dSVI 5 (mL/g)'[others$'NAB4 and 9 C-Pass dSVI 5 (mL/g)' == 0] <- NA
others <- others %>% select(-'NAB4 C-Pass dSVI 5 (mL/g)', -'NAB9 C-Pass dSVI 5 (mL/g)')

# c-pass TSS


others$`NAB9 C-Pass TSS (LAB) (mg/L)`[is.na(others$`NAB9 C-Pass TSS (LAB) (mg/L)`)] <- 0
others$`NAB4 C-Pass TSS (LAB) (mg/L)`[is.na(others$`NAB4 C-Pass TSS (LAB) (mg/L)`)] <- 0

others <- mutate(others, "NAB4 and 9 C-Pass TSS (LAB) (mg/L)" = 
              (others$`NAB9 C-Pass TSS (LAB) (mg/L)` + others$`NAB4 C-Pass TSS (LAB) (mg/L)`))

others$'NAB4 and 9 C-Pass TSS (LAB) (mg/L)'[others$'NAB4 and 9 C-Pass TSS (LAB) (mg/L)' == 0] <- NA
others <- others %>% select(-'NAB9 C-Pass TSS (LAB) (mg/L)', -'NAB4 C-Pass TSS (LAB) (mg/L)')

#ABXA NO5


others$`AB4A NO5 (mg N/L)`[is.na(others$`AB4A NO5 (mg N/L)`)] <- 0
others$`AB9A NO5 (mg N/L)`[is.na(others$`AB9A NO5 (mg N/L)`)] <- 0

others <- mutate(others, "AB4 and 9A NO5 (mg N/L)" = 
              (others$`AB4A NO5 (mg N/L)` + others$`AB9A NO5 (mg N/L)`))

others$'AB4 and 9A NO5 (mg N/L)'[others$'AB4 and 9A NO5 (mg N/L)' == 0] <- NA
others <- others %>% select(-'AB4A NO5 (mg N/L)', -'AB9A NO5 (mg N/L)')

# ABXA NH3

others$`AB4A NH3 (mg N/L)`[c(1:143, 297:435)] <- 0
others$`AB9A NH3 (mg N/L)`[144:296] <- 0

others <- mutate(others, "AB4 and 9A NH3 (mg N/L)" = 
              (others$`AB4A NH3 (mg N/L)` + others$`AB9A NH3 (mg N/L)`))

others$'AB4 and 9A NH3 (mg N/L)'[others$'AB4 and 9A NH3 (mg N/L)' == 0] <- NA
others <- others %>% select(-'AB4A NH3 (mg N/L)', -'AB9A NH3 (mg N/L)')

#ABXC NH3


others$`AB4C NH3 (mg N/L)`[c(1:143, 298:435)] <- 0
others$`AB9C NH3 (mg N/L)`[144:297] <- 0

others <- mutate(others, "AB4 and 9C NH3 (mg N/L)" = 
              (others$`AB4C NH3 (mg N/L)` + others$`AB9C NH3 (mg N/L)`))

others$'AB4 and 9C NH3 (mg N/L)'[others$'AB4 and 9C NH3 (mg N/L)' == 0] <- NA
others <- others %>% select(-'AB4C NH3 (mg N/L)', -'AB9C NH3 (mg N/L)')

# ABX3 MLSS

others$`AB4C MLSS (mg N/L)`[c(1:143, 297:435)] <- 0
others$`AB9C MLSS (mg/L)`[143:296] <- 0

others <- mutate(others, "AB4 and 9C MLSS (mg N/L)" = 
              (others$`AB4C MLSS (mg N/L)` + others$`AB9C MLSS (mg/L)`))


others$'AB4 and 9C MLSS (mg N/L)'[others$'AB4 and 9C MLSS (mg N/L)' == 0] <- NA
others <- others %>% select(-'AB4C MLSS (mg N/L)', -'AB9C MLSS (mg/L)')

#ABX INF FLOW


others$`AB4 INF FLOW (MGD)`[c(1:143, 296:435)] <- 0
others$`AB9 INF FLOW (MGD)`[144:295] <- 0

others <- mutate(others, "AB4 and 9 INF FLOW (MGD)" = 
              (others$`AB4 INF FLOW (MGD)` + others$`AB9 INF FLOW (MGD)`))

others$'AB4 and 9 INF FLOW (MGD)'[others$'AB4 and 9 INF FLOW (MGD)' == 0] <- NA
others <- others %>% select(-'AB4 INF FLOW (MGD)', -'AB9 INF FLOW (MGD)')

#ABX MLR FLOW

others$`AB4 MLR FLOW (MGD)`[297:435] <- 0
others$`AB9 MLR FLOW (MGD)`[1:296] <- 0

others <- mutate(others, "AB4 and 9 MLR FLOW (MGD)" = 
              (others$`AB4 MLR FLOW (MGD)` + others$`AB9 MLR FLOW (MGD)`))

others$'AB4 and 9 MLR FLOW (MGD)'[others$'AB4 and 9 MLR FLOW (MGD)' == 0] <- NA
others <- others %>% select(-'AB4 MLR FLOW (MGD)', -'AB9 MLR FLOW (MGD)')

#C-Pass VSS

others$`NAB4 C-Pass VSS (LAB) (mg/L)`[is.na(others$`NAB4 C-Pass VSS (LAB) (mg/L)`)] <- 0
others$`NAB9 C-Pass VSS (LAB) (mg/L)`[is.na(others$`NAB9 C-Pass VSS (LAB) (mg/L)`)] <- 0

others <- mutate(others, "NAB4 and 9 C-Pass VSS (LAB) (mg/L)" = 
              (others$`NAB4 C-Pass VSS (LAB) (mg/L)` + others$`NAB9 C-Pass VSS (LAB) (mg/L)`))

others$'NAB4 and 9 C-Pass VSS (LAB) (mg/L)'[others$'NAB4 and 9 C-Pass VSS (LAB) (mg/L)' == 0] <- NA
others <- others %>% select(-'NAB4 C-Pass VSS (LAB) (mg/L)', -'NAB9 C-Pass VSS (LAB) (mg/L)')

#C-Pass total COD


others$`NAB4 C-Pass Total COD (LAB) (mg/L)`[is.na(others$`NAB4 C-Pass Total COD (LAB) (mg/L)`)] <- 0
others$`NAB9 C-Pass Total COD (LAB) (mg/L)`[is.na(others$`NAB9 C-Pass Total COD (LAB) (mg/L)`)] <- 0

others <- mutate(others, "NAB4 and 9 C-Pass Total COD (LAB) (mg/L)" = 
              (others$`NAB4 C-Pass Total COD (LAB) (mg/L)` + others$`NAB9 C-Pass Total COD (LAB) (mg/L)`))

others$'NAB4 and 9 C-Pass Total COD (LAB) (mg/L)'[others$'NAB4 and 9 C-Pass Total COD (LAB) (mg/L)' == 0] <- NA
others <- others %>% select(-'NAB4 C-Pass Total COD (LAB) (mg/L)', -'NAB9 C-Pass Total COD (LAB) (mg/L)')



colnames(others) <- new_names_vector <- c(
  "timestamp",
  "CLARIFIER_9_SLR",
  "CLARIFIER_9_SOR",
  "NAB4_and_9_CPASS_TOTAL_COD",
  "NAB4_and_9_CPASS_VSS",
  "AB9A_DO",
  "AB9B_DO",
  "AB9C_DO",
  "AB9A_AIRFLOW",
  "AB9B_AIRFLOW",
  "AB9C_AIRFLOW",
  "SC9_BLANKET",
  "NNE_TOTAL_COD",
  "NNE_NH3A",
  "NNE_NO2",
  "NNE_NO5",
  "NNE_OP",
  "NNE_PWS",
  "NNE_PW",
  "NNE_TKNH",
  "NNE_TSS",
  "NNE_VSS",
  "NAB4_and_9_CPASS_TKNH",
  "NAB4_and_9_CPASS_dSVI30",
  "NAB4_and_9_CPASS_dSVI5",
  "NAB4_and_9_CPASS_TSS",
  "AB4_and_9A_NO5",
  "AB4_and_9A_NH3",
  "AB4_and_9C_NH3",
  "AB4_and_9C_MLSS",
  "AB4_and_9_INF_FLOW",
  "AB4_and_9_MLR_FLOW"
)

# Reorder to match correspongind pilot variables
others <- others %>%
  select(
    timestamp,
    CLARIFIER_9_SLR,
    CLARIFIER_9_SOR,
    NAB4_and_9_CPASS_TOTAL_COD,
    NAB4_and_9_CPASS_TKNH,
    NAB4_and_9_CPASS_TSS,
    NAB4_and_9_CPASS_VSS,
    AB9A_DO,
    AB9B_DO,
    AB9C_DO,
    AB4_and_9A_NO5,
    AB4_and_9A_NH3,
    AB4_and_9C_NH3,
    AB4_and_9C_MLSS,
    AB4_and_9_INF_FLOW,
    AB4_and_9_MLR_FLOW,
    AB9A_AIRFLOW,
    AB9B_AIRFLOW,
    AB9C_AIRFLOW,
    SC9_BLANKET,
    NAB4_and_9_CPASS_dSVI30,
    NAB4_and_9_CPASS_dSVI5,
    NNE_TOTAL_COD,
    NNE_NH3A,
    NNE_NO2,
    NNE_NO5,
    NNE_OP,
    NNE_PWS,
    NNE_PW,
    NNE_TKNH,
    NNE_TSS,
    NNE_VSS
  )

others <- others %>%
  mutate(across(-1, ~ ifelse(row_number() >= 1, na.locf(.), .)))

#get other ASRT variables for pilot
ASRT_other_control <- ASRT_other %>% select(timestamp, starts_with("Control"))
colnames(ASRT_other_control) <- c("timestamp",
                                "Control_ASRT_d",
                                "Control_Floc_SRT_d",
                                "Control_Granule_SRT_d",
                                "Control_AGS_Weighted_SRT_d",
                                "Control_Floc_percent",
                                "Control_Granule_percent")

#select Control ecoli and eps
control_ecoli <- ecoli %>% select(timestamp, log_control_reduction, log_control_ecoli)
control_factors <- left_join(control_ecoli, control_eps, by = "timestamp")
colnames(control_factors) <- c("timestamp", "log_control_reduction", 
                  "log_control_ecoli", "control_total_cod_mgcod_per_gvss",
                  "control_total_pn_to_ps", "control_lb_cod_mgcod_per_gvss",
                  "control_lb_proteins_mg_per_gvss", "control_lb_carbs_mg_per_gvss",
                  "control_tb_cod_mgcod_per_gvss", "control_tb_proteins_mg_per_gvss",
                  "control_tb_carbs_mgcarb_per_gvss", "control_tb_pn_to_ps")


#FILL method to fill in missing EPS and ASRT values
control_eps_filled <- left_join(control_factors, others, by = "timestamp")
control_eps_filled <- left_join(control_eps_filled, general, by = "timestamp")
control_eps_filled <- left_join(control_eps_filled, ASRT_main[,-2], by = "timestamp")
control_eps_filled <- left_join(control_eps_filled, ASRT_other_control, by = "timestamp")
control_eps_filled <- control_eps_filled %>% fill(-c("Control_NSEC_ASRT",
                                                     "control_total_cod_mgcod_per_gvss",
                  "control_total_pn_to_ps", "control_lb_cod_mgcod_per_gvss",
                  "control_lb_proteins_mg_per_gvss", "control_lb_carbs_mg_per_gvss",
                  "control_tb_cod_mgcod_per_gvss", "control_tb_proteins_mg_per_gvss",
                  "control_tb_carbs_mgcarb_per_gvss", "control_tb_pn_to_ps"
                                                     ), .direction = "down")
control_eps_filled <- control_eps_filled[-c(1:7),]
control_eps_filled <- control_eps_filled %>% fill(everything(), .direction = "down")

#REMOVE method
control_eps_removed <- left_join(control_factors, others, by = "timestamp")
control_eps_removed <- left_join(control_eps_removed, general, by = "timestamp")
control_eps_removed <- left_join(control_eps_removed, ASRT_main[,-2], by = "timestamp")
control_eps_removed <- left_join(control_eps_removed, ASRT_other_control, by = "timestamp")
control_eps_removed <- na.omit(control_eps_removed)

```

Combine Control and Pilot FIIL data with each system being a factorial variable
```{r}

#Combine for FILL data


# Mutate 'system' variable to be a factor with all 2s for pilot and all 9s for control
pilot_eps_filled <- pilot_eps_filled %>%
  mutate(system = factor(rep(2, nrow(pilot_eps_filled))))

control_eps_filled <- control_eps_filled %>%
  mutate(system = factor(rep(9, nrow(control_eps_filled))))


#change both dataframe names to match

new_column_names <- c(
"timestamp"                              
,"log_reduction"                   
,"log_ecoli"                        
,"total_cod_mgcod_per_gvss"        
,"total_pn_to_ps"                   
,"lb_cod_mgcod_per_gvss"           
,"lb_proteins_mg_per_gvss"          
,"lb_carbs_mg_per_gvss"            
,"tb_cod_mgcod_per_gvss"            
,"tb_proteins_mg_per_gvss"         
,"tb_carbs_mgcarb_per_gvss"         
,"tb_pn_to_ps"                     
,"CLARIFIER_X_SLR"                        
,"CLARIFIER_X_SOR"                       
,"NABX_CPASS_TOTAL_COD"                   
,"NABX_CPASS_TKNH"                       
,"NABX_CPASS_TSS"                         
,"NABX_CPASS_VSS"                        
,"ABXA_DO"                                
,"ABXB_DO"                               
,"ABXC_DO"                                
,"ABXA_NO5"                              
,"ABXA_NH3"                               
,"ABXC_NH3"                              
,"ABXC_MLSS"                              
,"ABX_INF_FLOW"                          
,"ABX_MLR_FLOW"                           
,"ABXA_AIRFLOW"                          
,"ABXB_AIRFLOW"                           
,"ABXC_AIRFLOW"                          
,"SCX_BLANKET"                            
,"NABX_CPASS_dSVI30"                     
,"NABX_CPASS_dSVI5"                       
,"NABX_CLARIFIER_EFFLUENT_TOTAL_COD"     
,"NABX_CLARIFIER_EFFLUENT_NH3"            
,"NABX_CLARIFIER_EFFLUENT_NO2"           
,"NABX_CLARIFIER_EFFLUENT_NO5"            
,"NABX_CLARIFIER_EFFLUENT_OP"            
,"NABX_CLARIFIER_EFFLUENT_PWS"            
,"NABX_CLARIFIER_EFFLUENT_PW"            
,"NABX_CLARIFIER_EFFLUENT_TKNH"           
,"NABX_CLARIFIER_EFFLUENT_TSS"           
,"NABX_CLARIFIER_EFFLUENT_VSS"            
,"NSEC ACTUAL ASRT (days)"               
,"Solids Wasted via Effluent (tpd)"       
,"Solids Wasted via SWAS (tpd)"          
,"Solids Wasted via WAS (tpd)"            
,"NSEC MIN ASRT (days)"                  
,"Total Solids Wasted (tpd)"              
,"NSI Soluble COD (LAB) (mg/L)"          
,"NSI Total COD (LAB) (mg/L)"             
,"NSI E. coli (LAB) (EC/100mL)"          
,"NSI NH3A (LAB) (mg/L)"                  
,"NSI NO2 (LAB) (mg/L)"                  
,"NSI NO5 (LAB) (mg/L)"                   
,"NSI OP (LAB) (mg/L)"                   
,"NSI PWS (LAB) (mg/L)"                   
,"NSI PW (LAB) (mg/L)"                   
,"NSI TKNH (LAB) (mg/L)"                  
,"NSI TSS (LAB) (mg/L)"                  
,"NSI TVAH (LAB) (mg/L)"                  
,"NSI VSS (LAB) (mg/L)"                  
,"NSEC EFF TSS (mg/L)"                    
,"NSI NH3 (mg N/L)"                      
,"NSI TSS (mg/L)"                         
,"NSI COD (mg/L)"                        
,"NSI sCOD (mg/L)"                        
,"NSI FLOW (MGD)"                        
,"NSI TEMP (C)"                           
,"NAB2_ASRT"                       
,"ASRT_d"                           
,"Floc_SRT_d"                      
,"Granule_SRT_d"                    
,"AGS_Weighted_SRT_d"              
,"Floc_percent"                     
,"Granule_percent"  
,"system"
                      )  # New column names

pilot_eps_filled <- setNames(pilot_eps_filled, new_column_names)
control_eps_filled <- setNames(control_eps_filled, new_column_names)

# Stack the dataframes vertically and change column names
all_eps_filled <- rbind(pilot_eps_filled, control_eps_filled)


## add day of the year variable and day of the week variable
all_eps_filled$timestamp <- as.Date(all_eps_filled$timestamp, format = "%Y/%m/%d")

all_eps_filled <- all_eps_filled %>%
  mutate(
    day_of_week = wday(timestamp),
    day_of_week = factor(day_of_week),
    month = month(timestamp),
    month = factor(month)
  )

all_eps_filled <- na.omit(all_eps_filled)

```


Combine Control and Pilot REMOVE data with each system being a factorial variable
```{r}

#Combine for REMOVE data


# Mutate 'system' variable to be a factor with all 2s for pilot and all 9s for control
pilot_eps_removed <- pilot_eps_removed %>%
  mutate(system = factor(rep(2, nrow(pilot_eps_removed))))

control_eps_removed <- control_eps_removed %>%
  mutate(system = factor(rep(9, nrow(control_eps_removed))))


#change both dataframe names to match

new_column_names <- c(
"timestamp"                              
,"log_reduction"                   
,"log_ecoli"                        
,"total_cod_mgcod_per_gvss"        
,"total_pn_to_ps"                   
,"lb_cod_mgcod_per_gvss"           
,"lb_proteins_mg_per_gvss"          
,"lb_carbs_mg_per_gvss"            
,"tb_cod_mgcod_per_gvss"            
,"tb_proteins_mg_per_gvss"         
,"tb_carbs_mgcarb_per_gvss"         
,"tb_pn_to_ps"                     
,"CLARIFIER_X_SLR"                        
,"CLARIFIER_X_SOR"                       
,"NABX_CPASS_TOTAL_COD"                   
,"NABX_CPASS_TKNH"                       
,"NABX_CPASS_TSS"                         
,"NABX_CPASS_VSS"                        
,"ABXA_DO"                                
,"ABXB_DO"                               
,"ABXC_DO"                                
,"ABXA_NO5"                              
,"ABXA_NH3"                               
,"ABXC_NH3"                              
,"ABXC_MLSS"                              
,"ABX_INF_FLOW"                          
,"ABX_MLR_FLOW"                           
,"ABXA_AIRFLOW"                          
,"ABXB_AIRFLOW"                           
,"ABXC_AIRFLOW"                          
,"SCX_BLANKET"                            
,"NABX_CPASS_dSVI30"                     
,"NABX_CPASS_dSVI5"                       
,"NABX_CLARIFIER_EFFLUENT_TOTAL_COD"     
,"NABX_CLARIFIER_EFFLUENT_NH3"            
,"NABX_CLARIFIER_EFFLUENT_NO2"           
,"NABX_CLARIFIER_EFFLUENT_NO5"            
,"NABX_CLARIFIER_EFFLUENT_OP"            
,"NABX_CLARIFIER_EFFLUENT_PWS"            
,"NABX_CLARIFIER_EFFLUENT_PW"            
,"NABX_CLARIFIER_EFFLUENT_TKNH"           
,"NABX_CLARIFIER_EFFLUENT_TSS"           
,"NABX_CLARIFIER_EFFLUENT_VSS"            
,"NSEC ACTUAL ASRT (days)"               
,"Solids Wasted via Effluent (tpd)"       
,"Solids Wasted via SWAS (tpd)"          
,"Solids Wasted via WAS (tpd)"            
,"NSEC MIN ASRT (days)"                  
,"Total Solids Wasted (tpd)"              
,"NSI Soluble COD (LAB) (mg/L)"          
,"NSI Total COD (LAB) (mg/L)"             
,"NSI E. coli (LAB) (EC/100mL)"          
,"NSI NH3A (LAB) (mg/L)"                  
,"NSI NO2 (LAB) (mg/L)"                  
,"NSI NO5 (LAB) (mg/L)"                   
,"NSI OP (LAB) (mg/L)"                   
,"NSI PWS (LAB) (mg/L)"                   
,"NSI PW (LAB) (mg/L)"                   
,"NSI TKNH (LAB) (mg/L)"                  
,"NSI TSS (LAB) (mg/L)"                  
,"NSI TVAH (LAB) (mg/L)"                  
,"NSI VSS (LAB) (mg/L)"                  
,"NSEC EFF TSS (mg/L)"                    
,"NSI NH3 (mg N/L)"                      
,"NSI TSS (mg/L)"                         
,"NSI COD (mg/L)"                        
,"NSI sCOD (mg/L)"                        
,"NSI FLOW (MGD)"                        
,"NSI TEMP (C)"                           
,"NAB2_ASRT"                       
,"ASRT_d"                           
,"Floc_SRT_d"                      
,"Granule_SRT_d"                    
,"AGS_Weighted_SRT_d"              
,"Floc_percent"                     
,"Granule_percent"  
,"system"
                      )  # New column names

pilot_eps_removed <- setNames(pilot_eps_removed, new_column_names)
control_eps_removed <- setNames(control_eps_removed, new_column_names)

# Stack the dataframes vertically and change column names
all_eps_removed <- rbind(pilot_eps_removed, control_eps_removed)


## add day of the year variable and day of the week variable
all_eps_removed$timestamp <- as.Date(all_eps_removed$timestamp, format = "%Y/%m/%d")

all_eps_removed <- all_eps_removed %>%
  mutate(
    day_of_week = wday(timestamp),
    day_of_week = factor(day_of_week),
    month = month(timestamp),
    month = factor(month )
  )
```


Export dataframes as CSV files
```{r}
write.csv(all_eps_filled, file = "data/all_eps_filled.csv", row.names = FALSE)

write.csv(all_eps_removed, file = "data/all_eps_removed.csv", row.names = FALSE)
```

